"""add_shelter_table

Revision ID: a988bdaa5787
Revises: 
Create Date: 2026-03-19 19:50:45.635699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a988bdaa5787'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelters_city'), 'shelters', ['city'], unique=False)
    op.create_index(op.f('ix_shelters_email'), 'shelters', ['email'], unique=True)
    op.create_index(op.f('ix_shelters_name'), 'shelters', ['name'], unique=False)
    op.create_table('animals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shelter_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_neutered', sa.Boolean(), nullable=False),
    sa.Column('is_vaccinated', sa.Boolean(), nullable=False),
    sa.Column('is_microchipped', sa.Boolean(), nullable=False),
    sa.Column('health_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('character_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('adoption_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('adopted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("sex IN ('macho','hembra')", name='ck_animals_sex'),
    sa.CheckConstraint("size IN ('pequeño','mediano','grande')", name='ck_animals_size'),
    sa.CheckConstraint("status IN ('disponible','en_proceso','adoptado','eliminado')", name='ck_animals_status'),
    sa.CheckConstraint('age_months >= 0', name='ck_animals_age_positive'),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_shelter_id'), 'animals', ['shelter_id'], unique=False)
    op.create_index('ix_animals_shelter_status', 'animals', ['shelter_id', 'status'], unique=False)
    op.create_index(op.f('ix_animals_status'), 'animals', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shelter_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=500), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('adoptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adoptions_animal_id'), 'adoptions', ['animal_id'], unique=False)
    op.create_index(op.f('ix_adoptions_applicant_id'), 'adoptions', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_adoptions_status'), 'adoptions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adoptions_status'), table_name='adoptions')
    op.drop_index(op.f('ix_adoptions_applicant_id'), table_name='adoptions')
    op.drop_index(op.f('ix_adoptions_animal_id'), table_name='adoptions')
    op.drop_table('adoptions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_animals_status'), table_name='animals')
    op.drop_index('ix_animals_shelter_status', table_name='animals')
    op.drop_index(op.f('ix_animals_shelter_id'), table_name='animals')
    op.drop_table('animals')
    op.drop_index(op.f('ix_shelters_name'), table_name='shelters')
    op.drop_index(op.f('ix_shelters_email'), table_name='shelters')
    op.drop_index(op.f('ix_shelters_city'), table_name='shelters')
    op.drop_table('shelters')
    # ### end Alembic commands ###
